// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/common.proto
// Protobuf Java Version: 4.33.5

package dev.animedia.grpc.common;

@com.google.protobuf.Generated
public final class CommonProto extends com.google.protobuf.GeneratedFile {
  private CommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "CommonProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaginationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.common.PaginationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 page = 1;</code>
     * @return The page.
     */
    int getPage();

    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>string sort = 3;</code>
     * @return The sort.
     */
    java.lang.String getSort();
    /**
     * <code>string sort = 3;</code>
     * @return The bytes for sort.
     */
    com.google.protobuf.ByteString
        getSortBytes();
  }
  /**
   * Protobuf type {@code protos.common.PaginationRequest}
   */
  public static final class PaginationRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.common.PaginationRequest)
      PaginationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 5,
        /* suffix= */ "",
        "PaginationRequest");
    }
    // Use PaginationRequest.newBuilder() to construct.
    private PaginationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PaginationRequest() {
      sort_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.common.CommonProto.PaginationRequest.class, dev.animedia.grpc.common.CommonProto.PaginationRequest.Builder.class);
    }

    public static final int PAGE_FIELD_NUMBER = 1;
    private int page_ = 0;
    /**
     * <code>int32 page = 1;</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_ = 0;
    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    public static final int SORT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sort_ = "";
    /**
     * <code>string sort = 3;</code>
     * @return The sort.
     */
    @java.lang.Override
    public java.lang.String getSort() {
      java.lang.Object ref = sort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sort_ = s;
        return s;
      }
    }
    /**
     * <code>string sort = 3;</code>
     * @return The bytes for sort.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSortBytes() {
      java.lang.Object ref = sort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (page_ != 0) {
        output.writeInt32(1, page_);
      }
      if (size_ != 0) {
        output.writeInt32(2, size_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sort_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, sort_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, page_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, size_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sort_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.common.CommonProto.PaginationRequest)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.common.CommonProto.PaginationRequest other = (dev.animedia.grpc.common.CommonProto.PaginationRequest) obj;

      if (getPage()
          != other.getPage()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (!getSort()
          .equals(other.getSort())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + getSort().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.common.CommonProto.PaginationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.common.PaginationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.common.PaginationRequest)
        dev.animedia.grpc.common.CommonProto.PaginationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.common.CommonProto.PaginationRequest.class, dev.animedia.grpc.common.CommonProto.PaginationRequest.Builder.class);
      }

      // Construct using dev.animedia.grpc.common.CommonProto.PaginationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        page_ = 0;
        size_ = 0;
        sort_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationRequest_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationRequest getDefaultInstanceForType() {
        return dev.animedia.grpc.common.CommonProto.PaginationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationRequest build() {
        dev.animedia.grpc.common.CommonProto.PaginationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationRequest buildPartial() {
        dev.animedia.grpc.common.CommonProto.PaginationRequest result = new dev.animedia.grpc.common.CommonProto.PaginationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.animedia.grpc.common.CommonProto.PaginationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.page_ = page_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sort_ = sort_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.common.CommonProto.PaginationRequest) {
          return mergeFrom((dev.animedia.grpc.common.CommonProto.PaginationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.common.CommonProto.PaginationRequest other) {
        if (other == dev.animedia.grpc.common.CommonProto.PaginationRequest.getDefaultInstance()) return this;
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (!other.getSort().isEmpty()) {
          sort_ = other.sort_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                page_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                size_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                sort_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int page_ ;
      /**
       * <code>int32 page = 1;</code>
       * @return The page.
       */
      @java.lang.Override
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 1;</code>
       * @param value The page to set.
       * @return This builder for chaining.
       */
      public Builder setPage(int value) {

        page_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>int32 size = 2;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 2;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {

        size_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sort_ = "";
      /**
       * <code>string sort = 3;</code>
       * @return The sort.
       */
      public java.lang.String getSort() {
        java.lang.Object ref = sort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sort_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sort = 3;</code>
       * @return The bytes for sort.
       */
      public com.google.protobuf.ByteString
          getSortBytes() {
        java.lang.Object ref = sort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sort = 3;</code>
       * @param value The sort to set.
       * @return This builder for chaining.
       */
      public Builder setSort(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string sort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSort() {
        sort_ = getDefaultInstance().getSort();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string sort = 3;</code>
       * @param value The bytes for sort to set.
       * @return This builder for chaining.
       */
      public Builder setSortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.common.PaginationRequest)
    }

    // @@protoc_insertion_point(class_scope:protos.common.PaginationRequest)
    private static final dev.animedia.grpc.common.CommonProto.PaginationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.common.CommonProto.PaginationRequest();
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaginationRequest>
        PARSER = new com.google.protobuf.AbstractParser<PaginationRequest>() {
      @java.lang.Override
      public PaginationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaginationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaginationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.common.CommonProto.PaginationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaginationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.common.PaginationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 current_page = 1;</code>
     * @return The currentPage.
     */
    int getCurrentPage();

    /**
     * <code>int32 page_size = 2;</code>
     * @return The pageSize.
     */
    int getPageSize();

    /**
     * <code>int32 total_pages = 3;</code>
     * @return The totalPages.
     */
    int getTotalPages();

    /**
     * <code>int64 total_elements = 4;</code>
     * @return The totalElements.
     */
    long getTotalElements();

    /**
     * <code>bool has_next = 5;</code>
     * @return The hasNext.
     */
    boolean getHasNext();

    /**
     * <code>bool has_previous = 6;</code>
     * @return The hasPrevious.
     */
    boolean getHasPrevious();
  }
  /**
   * Protobuf type {@code protos.common.PaginationResponse}
   */
  public static final class PaginationResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.common.PaginationResponse)
      PaginationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 5,
        /* suffix= */ "",
        "PaginationResponse");
    }
    // Use PaginationResponse.newBuilder() to construct.
    private PaginationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PaginationResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.common.CommonProto.PaginationResponse.class, dev.animedia.grpc.common.CommonProto.PaginationResponse.Builder.class);
    }

    public static final int CURRENT_PAGE_FIELD_NUMBER = 1;
    private int currentPage_ = 0;
    /**
     * <code>int32 current_page = 1;</code>
     * @return The currentPage.
     */
    @java.lang.Override
    public int getCurrentPage() {
      return currentPage_;
    }

    public static final int PAGE_SIZE_FIELD_NUMBER = 2;
    private int pageSize_ = 0;
    /**
     * <code>int32 page_size = 2;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }

    public static final int TOTAL_PAGES_FIELD_NUMBER = 3;
    private int totalPages_ = 0;
    /**
     * <code>int32 total_pages = 3;</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }

    public static final int TOTAL_ELEMENTS_FIELD_NUMBER = 4;
    private long totalElements_ = 0L;
    /**
     * <code>int64 total_elements = 4;</code>
     * @return The totalElements.
     */
    @java.lang.Override
    public long getTotalElements() {
      return totalElements_;
    }

    public static final int HAS_NEXT_FIELD_NUMBER = 5;
    private boolean hasNext_ = false;
    /**
     * <code>bool has_next = 5;</code>
     * @return The hasNext.
     */
    @java.lang.Override
    public boolean getHasNext() {
      return hasNext_;
    }

    public static final int HAS_PREVIOUS_FIELD_NUMBER = 6;
    private boolean hasPrevious_ = false;
    /**
     * <code>bool has_previous = 6;</code>
     * @return The hasPrevious.
     */
    @java.lang.Override
    public boolean getHasPrevious() {
      return hasPrevious_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currentPage_ != 0) {
        output.writeInt32(1, currentPage_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(2, pageSize_);
      }
      if (totalPages_ != 0) {
        output.writeInt32(3, totalPages_);
      }
      if (totalElements_ != 0L) {
        output.writeInt64(4, totalElements_);
      }
      if (hasNext_ != false) {
        output.writeBool(5, hasNext_);
      }
      if (hasPrevious_ != false) {
        output.writeBool(6, hasPrevious_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currentPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, currentPage_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      if (totalPages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalPages_);
      }
      if (totalElements_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, totalElements_);
      }
      if (hasNext_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, hasNext_);
      }
      if (hasPrevious_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, hasPrevious_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.common.CommonProto.PaginationResponse)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.common.CommonProto.PaginationResponse other = (dev.animedia.grpc.common.CommonProto.PaginationResponse) obj;

      if (getCurrentPage()
          != other.getCurrentPage()) return false;
      if (getPageSize()
          != other.getPageSize()) return false;
      if (getTotalPages()
          != other.getTotalPages()) return false;
      if (getTotalElements()
          != other.getTotalElements()) return false;
      if (getHasNext()
          != other.getHasNext()) return false;
      if (getHasPrevious()
          != other.getHasPrevious()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENT_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentPage();
      hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPages();
      hash = (37 * hash) + TOTAL_ELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalElements());
      hash = (37 * hash) + HAS_NEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasNext());
      hash = (37 * hash) + HAS_PREVIOUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPrevious());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.PaginationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.common.CommonProto.PaginationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.common.PaginationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.common.PaginationResponse)
        dev.animedia.grpc.common.CommonProto.PaginationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.common.CommonProto.PaginationResponse.class, dev.animedia.grpc.common.CommonProto.PaginationResponse.Builder.class);
      }

      // Construct using dev.animedia.grpc.common.CommonProto.PaginationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        currentPage_ = 0;
        pageSize_ = 0;
        totalPages_ = 0;
        totalElements_ = 0L;
        hasNext_ = false;
        hasPrevious_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_PaginationResponse_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationResponse getDefaultInstanceForType() {
        return dev.animedia.grpc.common.CommonProto.PaginationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationResponse build() {
        dev.animedia.grpc.common.CommonProto.PaginationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.PaginationResponse buildPartial() {
        dev.animedia.grpc.common.CommonProto.PaginationResponse result = new dev.animedia.grpc.common.CommonProto.PaginationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.animedia.grpc.common.CommonProto.PaginationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.currentPage_ = currentPage_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pageSize_ = pageSize_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalPages_ = totalPages_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.totalElements_ = totalElements_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hasNext_ = hasNext_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.hasPrevious_ = hasPrevious_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.common.CommonProto.PaginationResponse) {
          return mergeFrom((dev.animedia.grpc.common.CommonProto.PaginationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.common.CommonProto.PaginationResponse other) {
        if (other == dev.animedia.grpc.common.CommonProto.PaginationResponse.getDefaultInstance()) return this;
        if (other.getCurrentPage() != 0) {
          setCurrentPage(other.getCurrentPage());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getTotalPages() != 0) {
          setTotalPages(other.getTotalPages());
        }
        if (other.getTotalElements() != 0L) {
          setTotalElements(other.getTotalElements());
        }
        if (other.getHasNext() != false) {
          setHasNext(other.getHasNext());
        }
        if (other.getHasPrevious() != false) {
          setHasPrevious(other.getHasPrevious());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                currentPage_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                pageSize_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalPages_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                totalElements_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                hasNext_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                hasPrevious_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int currentPage_ ;
      /**
       * <code>int32 current_page = 1;</code>
       * @return The currentPage.
       */
      @java.lang.Override
      public int getCurrentPage() {
        return currentPage_;
      }
      /**
       * <code>int32 current_page = 1;</code>
       * @param value The currentPage to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentPage(int value) {

        currentPage_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 current_page = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentPage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentPage_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>int32 page_size = 2;</code>
       * @return The pageSize.
       */
      @java.lang.Override
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>int32 page_size = 2;</code>
       * @param value The pageSize to set.
       * @return This builder for chaining.
       */
      public Builder setPageSize(int value) {

        pageSize_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page_size = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int totalPages_ ;
      /**
       * <code>int32 total_pages = 3;</code>
       * @return The totalPages.
       */
      @java.lang.Override
      public int getTotalPages() {
        return totalPages_;
      }
      /**
       * <code>int32 total_pages = 3;</code>
       * @param value The totalPages to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPages(int value) {

        totalPages_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_pages = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPages() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPages_ = 0;
        onChanged();
        return this;
      }

      private long totalElements_ ;
      /**
       * <code>int64 total_elements = 4;</code>
       * @return The totalElements.
       */
      @java.lang.Override
      public long getTotalElements() {
        return totalElements_;
      }
      /**
       * <code>int64 total_elements = 4;</code>
       * @param value The totalElements to set.
       * @return This builder for chaining.
       */
      public Builder setTotalElements(long value) {

        totalElements_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 total_elements = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalElements() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalElements_ = 0L;
        onChanged();
        return this;
      }

      private boolean hasNext_ ;
      /**
       * <code>bool has_next = 5;</code>
       * @return The hasNext.
       */
      @java.lang.Override
      public boolean getHasNext() {
        return hasNext_;
      }
      /**
       * <code>bool has_next = 5;</code>
       * @param value The hasNext to set.
       * @return This builder for chaining.
       */
      public Builder setHasNext(boolean value) {

        hasNext_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool has_next = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasNext() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasNext_ = false;
        onChanged();
        return this;
      }

      private boolean hasPrevious_ ;
      /**
       * <code>bool has_previous = 6;</code>
       * @return The hasPrevious.
       */
      @java.lang.Override
      public boolean getHasPrevious() {
        return hasPrevious_;
      }
      /**
       * <code>bool has_previous = 6;</code>
       * @param value The hasPrevious to set.
       * @return This builder for chaining.
       */
      public Builder setHasPrevious(boolean value) {

        hasPrevious_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool has_previous = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasPrevious() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hasPrevious_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.common.PaginationResponse)
    }

    // @@protoc_insertion_point(class_scope:protos.common.PaginationResponse)
    private static final dev.animedia.grpc.common.CommonProto.PaginationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.common.CommonProto.PaginationResponse();
    }

    public static dev.animedia.grpc.common.CommonProto.PaginationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaginationResponse>
        PARSER = new com.google.protobuf.AbstractParser<PaginationResponse>() {
      @java.lang.Override
      public PaginationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaginationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaginationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.common.CommonProto.PaginationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.common.EmptyResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protos.common.EmptyResponse}
   */
  public static final class EmptyResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.common.EmptyResponse)
      EmptyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 5,
        /* suffix= */ "",
        "EmptyResponse");
    }
    // Use EmptyResponse.newBuilder() to construct.
    private EmptyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EmptyResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_EmptyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_EmptyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.common.CommonProto.EmptyResponse.class, dev.animedia.grpc.common.CommonProto.EmptyResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.common.CommonProto.EmptyResponse)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.common.CommonProto.EmptyResponse other = (dev.animedia.grpc.common.CommonProto.EmptyResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.common.CommonProto.EmptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.common.CommonProto.EmptyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.common.EmptyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.common.EmptyResponse)
        dev.animedia.grpc.common.CommonProto.EmptyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_EmptyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_EmptyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.common.CommonProto.EmptyResponse.class, dev.animedia.grpc.common.CommonProto.EmptyResponse.Builder.class);
      }

      // Construct using dev.animedia.grpc.common.CommonProto.EmptyResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.common.CommonProto.internal_static_protos_common_EmptyResponse_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.EmptyResponse getDefaultInstanceForType() {
        return dev.animedia.grpc.common.CommonProto.EmptyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.EmptyResponse build() {
        dev.animedia.grpc.common.CommonProto.EmptyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.common.CommonProto.EmptyResponse buildPartial() {
        dev.animedia.grpc.common.CommonProto.EmptyResponse result = new dev.animedia.grpc.common.CommonProto.EmptyResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.common.CommonProto.EmptyResponse) {
          return mergeFrom((dev.animedia.grpc.common.CommonProto.EmptyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.common.CommonProto.EmptyResponse other) {
        if (other == dev.animedia.grpc.common.CommonProto.EmptyResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.common.EmptyResponse)
    }

    // @@protoc_insertion_point(class_scope:protos.common.EmptyResponse)
    private static final dev.animedia.grpc.common.CommonProto.EmptyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.common.CommonProto.EmptyResponse();
    }

    public static dev.animedia.grpc.common.CommonProto.EmptyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyResponse>
        PARSER = new com.google.protobuf.AbstractParser<EmptyResponse>() {
      @java.lang.Override
      public EmptyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EmptyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.common.CommonProto.EmptyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_common_PaginationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_common_PaginationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_common_PaginationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_common_PaginationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_common_EmptyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_common_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/common.proto\022\rprotos.common\"=\n\021" +
      "PaginationRequest\022\014\n\004page\030\001 \001(\005\022\014\n\004size\030" +
      "\002 \001(\005\022\014\n\004sort\030\003 \001(\t\"\222\001\n\022PaginationRespon" +
      "se\022\024\n\014current_page\030\001 \001(\005\022\021\n\tpage_size\030\002 " +
      "\001(\005\022\023\n\013total_pages\030\003 \001(\005\022\026\n\016total_elemen" +
      "ts\030\004 \001(\003\022\020\n\010has_next\030\005 \001(\010\022\024\n\014has_previo" +
      "us\030\006 \001(\010\"\017\n\rEmptyResponseB\'\n\030dev.animedi" +
      "a.grpc.commonB\013CommonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_common_PaginationRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_protos_common_PaginationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_common_PaginationRequest_descriptor,
        new java.lang.String[] { "Page", "Size", "Sort", });
    internal_static_protos_common_PaginationResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_protos_common_PaginationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_common_PaginationResponse_descriptor,
        new java.lang.String[] { "CurrentPage", "PageSize", "TotalPages", "TotalElements", "HasNext", "HasPrevious", });
    internal_static_protos_common_EmptyResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_protos_common_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_common_EmptyResponse_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
