syntax = "proto3";

package protos.common;

import "google/protobuf/any.proto";

//option java_multiple_files=true;
option java_package="dev.animedia.grpc.common";
option java_outer_classname="CommonProto";

message AppRequest {
  google.protobuf.Any data = 1;
  optional string language_code = 2;
  optional PaginationRequest pagination = 3;
}

message PaginationRequest {
  int32 page = 1;
  int32 size = 2;
  string sort = 3;
}

message AppResponse {
  bool success = 1;
  google.protobuf.Any data = 2;
  repeated string errors = 3;
  optional PaginationResponse pagination = 4;
}

message PaginationResponse {
  int32 current_page = 1;
  int32 page_size = 2;
  int32 total_pages = 3;
  int64 total_elements = 4;
  bool has_next = 5;
  bool has_previous = 6;
}