syntax = "proto3";

package protos.common;

import "google/protobuf/any.proto";

option java_package="dev.animedia.grpc.common";
option java_outer_classname="CommonProto";

message PaginationRequest {
  int64 page = 1;
  int64 size = 2;
  Sort sort = 3;
}

message PaginationResponse {
  repeated google.protobuf.Any content = 1;
  int64 current_page = 2;
  int64 page_size = 3;
  int64 total_pages = 4;
  int64 total_elements = 5;
  bool has_next = 6;
  bool has_previous = 7;
}

message Date {
  int32 year = 1;
  int32 month = 2;
  int32 day = 3;
}

message EmptyResponse {}

message Sort {
  string field = 1;
  SortDirection direction = 2;
}

enum SortDirection {
  DESC = 0;
  ASC = 1;
}