// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/content/genre/genre_common.proto
// Protobuf Java Version: 4.33.2

package dev.animedia.grpc.genre;

@com.google.protobuf.Generated
public final class GenreCommonProto extends com.google.protobuf.GeneratedFile {
  private GenreCommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "GenreCommonProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenreResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.services.content.genre.GenreResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string alias = 2;</code>
     * @return The alias.
     */
    java.lang.String getAlias();
    /**
     * <code>string alias = 2;</code>
     * @return The bytes for alias.
     */
    com.google.protobuf.ByteString
        getAliasBytes();

    /**
     * <code>int64 sort = 3;</code>
     * @return The sort.
     */
    long getSort();
  }
  /**
   * Protobuf type {@code protos.services.content.genre.GenreResponse}
   */
  public static final class GenreResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.services.content.genre.GenreResponse)
      GenreResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 2,
        /* suffix= */ "",
        "GenreResponse");
    }
    // Use GenreResponse.newBuilder() to construct.
    private GenreResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GenreResponse() {
      alias_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.class, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int ALIAS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object alias_ = "";
    /**
     * <code>string alias = 2;</code>
     * @return The alias.
     */
    @java.lang.Override
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      }
    }
    /**
     * <code>string alias = 2;</code>
     * @return The bytes for alias.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SORT_FIELD_NUMBER = 3;
    private long sort_ = 0L;
    /**
     * <code>int64 sort = 3;</code>
     * @return The sort.
     */
    @java.lang.Override
    public long getSort() {
      return sort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, alias_);
      }
      if (sort_ != 0L) {
        output.writeInt64(3, sort_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, alias_);
      }
      if (sort_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreResponse)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.genre.GenreCommonProto.GenreResponse other = (dev.animedia.grpc.genre.GenreCommonProto.GenreResponse) obj;

      if (getId()
          != other.getId()) return false;
      if (!getAlias()
          .equals(other.getAlias())) return false;
      if (getSort()
          != other.getSort()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + ALIAS_FIELD_NUMBER;
      hash = (53 * hash) + getAlias().hashCode();
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSort());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.genre.GenreCommonProto.GenreResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.services.content.genre.GenreResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.services.content.genre.GenreResponse)
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.class, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder.class);
      }

      // Construct using dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        alias_ = "";
        sort_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponse_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getDefaultInstanceForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse build() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse buildPartial() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponse result = new dev.animedia.grpc.genre.GenreCommonProto.GenreResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.animedia.grpc.genre.GenreCommonProto.GenreResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.alias_ = alias_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sort_ = sort_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreResponse) {
          return mergeFrom((dev.animedia.grpc.genre.GenreCommonProto.GenreResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.genre.GenreCommonProto.GenreResponse other) {
        if (other == dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getAlias().isEmpty()) {
          alias_ = other.alias_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getSort() != 0L) {
          setSort(other.getSort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                alias_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                sort_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object alias_ = "";
      /**
       * <code>string alias = 2;</code>
       * @return The alias.
       */
      public java.lang.String getAlias() {
        java.lang.Object ref = alias_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alias_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alias = 2;</code>
       * @return The bytes for alias.
       */
      public com.google.protobuf.ByteString
          getAliasBytes() {
        java.lang.Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alias = 2;</code>
       * @param value The alias to set.
       * @return This builder for chaining.
       */
      public Builder setAlias(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        alias_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string alias = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlias() {
        alias_ = getDefaultInstance().getAlias();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string alias = 2;</code>
       * @param value The bytes for alias to set.
       * @return This builder for chaining.
       */
      public Builder setAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        alias_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long sort_ ;
      /**
       * <code>int64 sort = 3;</code>
       * @return The sort.
       */
      @java.lang.Override
      public long getSort() {
        return sort_;
      }
      /**
       * <code>int64 sort = 3;</code>
       * @param value The sort to set.
       * @return This builder for chaining.
       */
      public Builder setSort(long value) {

        sort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sort_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.services.content.genre.GenreResponse)
    }

    // @@protoc_insertion_point(class_scope:protos.services.content.genre.GenreResponse)
    private static final dev.animedia.grpc.genre.GenreCommonProto.GenreResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.genre.GenreCommonProto.GenreResponse();
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenreResponse>
        PARSER = new com.google.protobuf.AbstractParser<GenreResponse>() {
      @java.lang.Override
      public GenreResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenreResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenreResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenreResponseListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.services.content.genre.GenreResponseList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> 
        getGenresList();
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getGenres(int index);
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    int getGenresCount();
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    java.util.List<? extends dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder> 
        getGenresOrBuilderList();
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder getGenresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protos.services.content.genre.GenreResponseList}
   */
  public static final class GenreResponseList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.services.content.genre.GenreResponseList)
      GenreResponseListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 2,
        /* suffix= */ "",
        "GenreResponseList");
    }
    // Use GenreResponseList.newBuilder() to construct.
    private GenreResponseList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GenreResponseList() {
      genres_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.class, dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.Builder.class);
    }

    public static final int GENRES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> genres_;
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    @java.lang.Override
    public java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> getGenresList() {
      return genres_;
    }
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder> 
        getGenresOrBuilderList() {
      return genres_;
    }
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    @java.lang.Override
    public int getGenresCount() {
      return genres_.size();
    }
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    @java.lang.Override
    public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getGenres(int index) {
      return genres_.get(index);
    }
    /**
     * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
     */
    @java.lang.Override
    public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder getGenresOrBuilder(
        int index) {
      return genres_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < genres_.size(); i++) {
        output.writeMessage(1, genres_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < genres_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, genres_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList other = (dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList) obj;

      if (!getGenresList()
          .equals(other.getGenresList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGenresCount() > 0) {
        hash = (37 * hash) + GENRES_FIELD_NUMBER;
        hash = (53 * hash) + getGenresList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.services.content.genre.GenreResponseList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.services.content.genre.GenreResponseList)
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponseListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponseList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponseList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.class, dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.Builder.class);
      }

      // Construct using dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (genresBuilder_ == null) {
          genres_ = java.util.Collections.emptyList();
        } else {
          genres_ = null;
          genresBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreResponseList_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList getDefaultInstanceForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList build() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList buildPartial() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList result = new dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList result) {
        if (genresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            genres_ = java.util.Collections.unmodifiableList(genres_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.genres_ = genres_;
        } else {
          result.genres_ = genresBuilder_.build();
        }
      }

      private void buildPartial0(dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList) {
          return mergeFrom((dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList other) {
        if (other == dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList.getDefaultInstance()) return this;
        if (genresBuilder_ == null) {
          if (!other.genres_.isEmpty()) {
            if (genres_.isEmpty()) {
              genres_ = other.genres_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGenresIsMutable();
              genres_.addAll(other.genres_);
            }
            onChanged();
          }
        } else {
          if (!other.genres_.isEmpty()) {
            if (genresBuilder_.isEmpty()) {
              genresBuilder_.dispose();
              genresBuilder_ = null;
              genres_ = other.genres_;
              bitField0_ = (bitField0_ & ~0x00000001);
              genresBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetGenresFieldBuilder() : null;
            } else {
              genresBuilder_.addAllMessages(other.genres_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                dev.animedia.grpc.genre.GenreCommonProto.GenreResponse m =
                    input.readMessage(
                        dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.parser(),
                        extensionRegistry);
                if (genresBuilder_ == null) {
                  ensureGenresIsMutable();
                  genres_.add(m);
                } else {
                  genresBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> genres_ =
        java.util.Collections.emptyList();
      private void ensureGenresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          genres_ = new java.util.ArrayList<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse>(genres_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          dev.animedia.grpc.genre.GenreCommonProto.GenreResponse, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder, dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder> genresBuilder_;

      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> getGenresList() {
        if (genresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(genres_);
        } else {
          return genresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public int getGenresCount() {
        if (genresBuilder_ == null) {
          return genres_.size();
        } else {
          return genresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse getGenres(int index) {
        if (genresBuilder_ == null) {
          return genres_.get(index);
        } else {
          return genresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder setGenres(
          int index, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse value) {
        if (genresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGenresIsMutable();
          genres_.set(index, value);
          onChanged();
        } else {
          genresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder setGenres(
          int index, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder builderForValue) {
        if (genresBuilder_ == null) {
          ensureGenresIsMutable();
          genres_.set(index, builderForValue.build());
          onChanged();
        } else {
          genresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder addGenres(dev.animedia.grpc.genre.GenreCommonProto.GenreResponse value) {
        if (genresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGenresIsMutable();
          genres_.add(value);
          onChanged();
        } else {
          genresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder addGenres(
          int index, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse value) {
        if (genresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGenresIsMutable();
          genres_.add(index, value);
          onChanged();
        } else {
          genresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder addGenres(
          dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder builderForValue) {
        if (genresBuilder_ == null) {
          ensureGenresIsMutable();
          genres_.add(builderForValue.build());
          onChanged();
        } else {
          genresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder addGenres(
          int index, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder builderForValue) {
        if (genresBuilder_ == null) {
          ensureGenresIsMutable();
          genres_.add(index, builderForValue.build());
          onChanged();
        } else {
          genresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder addAllGenres(
          java.lang.Iterable<? extends dev.animedia.grpc.genre.GenreCommonProto.GenreResponse> values) {
        if (genresBuilder_ == null) {
          ensureGenresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, genres_);
          onChanged();
        } else {
          genresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder clearGenres() {
        if (genresBuilder_ == null) {
          genres_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          genresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public Builder removeGenres(int index) {
        if (genresBuilder_ == null) {
          ensureGenresIsMutable();
          genres_.remove(index);
          onChanged();
        } else {
          genresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder getGenresBuilder(
          int index) {
        return internalGetGenresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder getGenresOrBuilder(
          int index) {
        if (genresBuilder_ == null) {
          return genres_.get(index);  } else {
          return genresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public java.util.List<? extends dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder> 
           getGenresOrBuilderList() {
        if (genresBuilder_ != null) {
          return genresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(genres_);
        }
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder addGenresBuilder() {
        return internalGetGenresFieldBuilder().addBuilder(
            dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder addGenresBuilder(
          int index) {
        return internalGetGenresFieldBuilder().addBuilder(
            index, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.services.content.genre.GenreResponse genres = 1;</code>
       */
      public java.util.List<dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder> 
           getGenresBuilderList() {
        return internalGetGenresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          dev.animedia.grpc.genre.GenreCommonProto.GenreResponse, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder, dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder> 
          internalGetGenresFieldBuilder() {
        if (genresBuilder_ == null) {
          genresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              dev.animedia.grpc.genre.GenreCommonProto.GenreResponse, dev.animedia.grpc.genre.GenreCommonProto.GenreResponse.Builder, dev.animedia.grpc.genre.GenreCommonProto.GenreResponseOrBuilder>(
                  genres_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          genres_ = null;
        }
        return genresBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protos.services.content.genre.GenreResponseList)
    }

    // @@protoc_insertion_point(class_scope:protos.services.content.genre.GenreResponseList)
    private static final dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList();
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenreResponseList>
        PARSER = new com.google.protobuf.AbstractParser<GenreResponseList>() {
      @java.lang.Override
      public GenreResponseList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenreResponseList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenreResponseList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.genre.GenreCommonProto.GenreResponseList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenreTranslationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.services.content.genre.GenreTranslationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 genre_id = 2;</code>
     * @return The genreId.
     */
    long getGenreId();

    /**
     * <code>string language_code = 3;</code>
     * @return The languageCode.
     */
    java.lang.String getLanguageCode();
    /**
     * <code>string language_code = 3;</code>
     * @return The bytes for languageCode.
     */
    com.google.protobuf.ByteString
        getLanguageCodeBytes();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code protos.services.content.genre.GenreTranslationResponse}
   */
  public static final class GenreTranslationResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.services.content.genre.GenreTranslationResponse)
      GenreTranslationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 2,
        /* suffix= */ "",
        "GenreTranslationResponse");
    }
    // Use GenreTranslationResponse.newBuilder() to construct.
    private GenreTranslationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GenreTranslationResponse() {
      languageCode_ = "";
      name_ = "";
      description_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreTranslationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.class, dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int GENRE_ID_FIELD_NUMBER = 2;
    private long genreId_ = 0L;
    /**
     * <code>int64 genre_id = 2;</code>
     * @return The genreId.
     */
    @java.lang.Override
    public long getGenreId() {
      return genreId_;
    }

    public static final int LANGUAGE_CODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object languageCode_ = "";
    /**
     * <code>string language_code = 3;</code>
     * @return The languageCode.
     */
    @java.lang.Override
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      }
    }
    /**
     * <code>string language_code = 3;</code>
     * @return The bytes for languageCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (genreId_ != 0L) {
        output.writeInt64(2, genreId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(languageCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, languageCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (genreId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, genreId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(languageCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, languageCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse)) {
        return super.equals(obj);
      }
      dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse other = (dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse) obj;

      if (getId()
          != other.getId()) return false;
      if (getGenreId()
          != other.getGenreId()) return false;
      if (!getLanguageCode()
          .equals(other.getLanguageCode())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + GENRE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGenreId());
      hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguageCode().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.services.content.genre.GenreTranslationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.services.content.genre.GenreTranslationResponse)
        dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreTranslationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.class, dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.Builder.class);
      }

      // Construct using dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        genreId_ = 0L;
        languageCode_ = "";
        name_ = "";
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse getDefaultInstanceForType() {
        return dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse build() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse buildPartial() {
        dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse result = new dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.genreId_ = genreId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.languageCode_ = languageCode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse) {
          return mergeFrom((dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse other) {
        if (other == dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getGenreId() != 0L) {
          setGenreId(other.getGenreId());
        }
        if (!other.getLanguageCode().isEmpty()) {
          languageCode_ = other.languageCode_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                genreId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                languageCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long genreId_ ;
      /**
       * <code>int64 genre_id = 2;</code>
       * @return The genreId.
       */
      @java.lang.Override
      public long getGenreId() {
        return genreId_;
      }
      /**
       * <code>int64 genre_id = 2;</code>
       * @param value The genreId to set.
       * @return This builder for chaining.
       */
      public Builder setGenreId(long value) {

        genreId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 genre_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenreId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        genreId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object languageCode_ = "";
      /**
       * <code>string language_code = 3;</code>
       * @return The languageCode.
       */
      public java.lang.String getLanguageCode() {
        java.lang.Object ref = languageCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          languageCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string language_code = 3;</code>
       * @return The bytes for languageCode.
       */
      public com.google.protobuf.ByteString
          getLanguageCodeBytes() {
        java.lang.Object ref = languageCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          languageCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language_code = 3;</code>
       * @param value The languageCode to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        languageCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string language_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguageCode() {
        languageCode_ = getDefaultInstance().getLanguageCode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string language_code = 3;</code>
       * @param value The bytes for languageCode to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        languageCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 5;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protos.services.content.genre.GenreTranslationResponse)
    }

    // @@protoc_insertion_point(class_scope:protos.services.content.genre.GenreTranslationResponse)
    private static final dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse();
    }

    public static dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenreTranslationResponse>
        PARSER = new com.google.protobuf.AbstractParser<GenreTranslationResponse>() {
      @java.lang.Override
      public GenreTranslationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenreTranslationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenreTranslationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.animedia.grpc.genre.GenreCommonProto.GenreTranslationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_services_content_genre_GenreResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_services_content_genre_GenreResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_services_content_genre_GenreResponseList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_services_content_genre_GenreResponseList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_services_content_genre_GenreTranslationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)services/content/genre/genre_common.pr" +
      "oto\022\035protos.services.content.genre\"8\n\rGe" +
      "nreResponse\022\n\n\002id\030\001 \001(\003\022\r\n\005alias\030\002 \001(\t\022\014" +
      "\n\004sort\030\003 \001(\003\"Q\n\021GenreResponseList\022<\n\006gen" +
      "res\030\001 \003(\0132,.protos.services.content.genr" +
      "e.GenreResponse\"r\n\030GenreTranslationRespo" +
      "nse\022\n\n\002id\030\001 \001(\003\022\020\n\010genre_id\030\002 \001(\003\022\025\n\rlan" +
      "guage_code\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\023\n\013descri" +
      "ption\030\005 \001(\tB+\n\027dev.animedia.grpc.genreB\020" +
      "GenreCommonProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_services_content_genre_GenreResponse_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_protos_services_content_genre_GenreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_services_content_genre_GenreResponse_descriptor,
        new java.lang.String[] { "Id", "Alias", "Sort", });
    internal_static_protos_services_content_genre_GenreResponseList_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_protos_services_content_genre_GenreResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_services_content_genre_GenreResponseList_descriptor,
        new java.lang.String[] { "Genres", });
    internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_protos_services_content_genre_GenreTranslationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_services_content_genre_GenreTranslationResponse_descriptor,
        new java.lang.String[] { "Id", "GenreId", "LanguageCode", "Name", "Description", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
