spring.application.name=language-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5445/language
spring.datasource.username=animedia
spring.datasource.password=password

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.threads.virtual.enabled=true

application.exception.locale.path=/errors/