spring.application.name=language-service

spring.grpc.server.port=9091

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5445/language
spring.datasource.username=animedia
spring.datasource.password=password

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.threads.virtual.enabled=true

application.exception.locale.path=C:/projects/animedia-backend/services/language-service/src/main/resources/errors