services:
  db_content:
    container_name: animedia_content_service_database
    image: postgres:18.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data_content:/var/lib/postgresql
    networks:
      - animedia_content_service

volumes:
  db_data_content:

networks:
  animedia_content_service:

