syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";
import "services/content/status/content_status_common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="ContentStatusPrivateProto";

service ContentStatusPrivateService {
  rpc search(SearchRequest) returns (SearchResponse);
  rpc create(CreateRequest) returns (ContentStatusResponse);
  rpc update(UpdateRequest) returns (ContentStatusResponse);
  rpc delete(DeleteRequest) returns (common.EmptyResponse);
}

message SearchRequest {
  repeated int64 ids = 1;
  repeated string language_codes = 2;
  optional string alias = 3;
  optional string name = 4;
  optional common.PaginationRequest pagination = 5;
}

message SearchResponse {
  repeated ContentStatusWithTranslations content_statuses = 1;
  common.PaginationResponse pagination = 2;
}

message ContentStatusWithTranslations {
  ContentStatusResponse content_status = 1;
  repeated ContentStatusTranslationResponse translations = 2;
}

message CreateRequest {
  string alias = 1;
}

message UpdateRequest {
  int64 id = 1;
  string alias = 2;
}

message DeleteRequest {
  int64 id = 1;
}