syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";
import "services/content/status/content_status_common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="ContentStatusPublicProto";

service ContentStatusPublicService {
  rpc search(SearchRequest) returns (SearchResponse);
}

message SearchRequest {
  optional string alias = 1;
  optional string name = 2;
  common.PaginationRequest pagination = 3;
}

message SearchResponse {
  repeated ContentStatusWithTranslationResponse content_statuses = 1;
  common.PaginationResponse pagination = 2;
}