syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";
import "services/content/status/content_status_common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="PrivateContentStatusTranslationProto";

service PrivateContentStatusTranslationService {
  rpc create(PrivateTranslationCreateRequest) returns (ContentStatusTranslationResponse);
  rpc update(PrivateTranslationUpdateRequest) returns (ContentStatusTranslationResponse);
  rpc delete(PrivateTranslationDeleteRequest) returns (common.EmptyResponse);
}

message PrivateTranslationCreateRequest {
  int64 content_status_id = 1;
  string language_code = 2;
  string name = 3;
}

message PrivateTranslationUpdateRequest {
  int64 id = 1;
  string name = 2;
}

message PrivateTranslationDeleteRequest {
  int64 id = 1;
}