syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";
import "services/content/status/content_status_common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="PrivateContentStatusProto";

service PrivateContentStatusService {
  rpc search(PrivateSearchRequest) returns (PrivateSearchResponse);
  rpc create(PrivateCreateRequest) returns (ContentStatusResponse);
  rpc update(PrivateUpdateRequest) returns (ContentStatusResponse);
  rpc delete(PrivateDeleteRequest) returns (common.EmptyResponse);
}

message PrivateSearchRequest {
  repeated int64 ids = 1;
  repeated string language_codes = 2;
  optional string alias = 3;
  optional string name = 4;
  optional common.PaginationRequest pagination = 5;
}

message PrivateSearchResponse {
  repeated ContentStatusWithTranslations content_statuses = 1;
  common.PaginationResponse pagination = 2;
}

message PrivateCreateRequest {
  string alias = 1;
}

message PrivateUpdateRequest {
  int64 id = 1;
  string alias = 2;
}

message PrivateDeleteRequest {
  int64 id = 1;
}