syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";
import "services/content/status/content_status_common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="PrivateContentStatusProto";

service PrivateContentStatusService {
  rpc search(PrivateSearchRequest) returns (PrivateSearchResponse);
  rpc create(PrivateCreateRequest) returns (ContentStatusResponse);
  rpc update(PrivateUpdateRequest) returns (ContentStatusResponse);
  rpc delete(PrivateDeleteRequest) returns (common.EmptyResponse);
}

message PrivateSearchRequest {
  bool only_active = 1;
  optional string alias = 2;
  optional string name = 3;
  repeated string language_codes = 4;
  optional common.PaginationRequest pagination = 5;
}

message PrivateSearchResponse {
  repeated ContentStatusResponse statuses = 1;
  common.PaginationResponse pagination = 2;
}

message PrivateCreateRequest {
  string alias = 1;
  int32 sort_order = 2;
  bool active = 3;
  repeated PrivateCreateTranslationRequest translations = 4;
}

message PrivateCreateTranslationRequest {
  string language_code = 1;
  string name = 2;
}

message PrivateUpdateRequest {
  int64 id = 1;
  int32 sort_order = 2;
  bool active = 3;
  repeated PrivateUpdateTranslationRequest translations = 4;
}

message PrivateUpdateTranslationRequest {
  int64 id = 1;
  string language_code = 2;
  string name = 3;
}

message PrivateDeleteRequest {
  int64 id = 1;
}