syntax = "proto3";

package protos.services.content.status;

import "common/common.proto";

option java_package="dev.animedia.grpc.status";
option java_outer_classname="PublicContentStatusProto";

service PublicContentStatusService {
  rpc search(PublicSearchStatusRequest) returns (PublicSearchStatusResponse);
}

message PublicStatusResponse {
  string alias = 1;
  repeated PublicStatusTranslationResponse translations = 2;
}

message PublicStatusTranslationResponse {
  string name = 4;
}

message PublicSearchStatusRequest {
  optional string alias = 1;
  optional string name = 2;
  common.PaginationRequest pagination = 3;
}

message PublicSearchStatusResponse {
  repeated PublicStatusResponse statuses = 1;
  common.PaginationResponse pagination = 2;
}