syntax = "proto3";

package protos.services.content.genre;

import "common/common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.genre";
option java_outer_classname="PrivateGenreProto";

service PrivateGenreService {
    rpc search(PrivateSearchRequest) returns (PrivateSearchResponse);

    rpc create(PrivateCreateRequest) returns (GenreResponse);
    rpc createBatch(PrivateCreateBatchRequest) returns (GenreResponseList);

    rpc update(PrivateUpdateRequest) returns (GenreResponse);

    rpc delete(PrivateDeleteRequest) returns (common.EmptyResponse);
    rpc deleteBatch(PrivateDeleteBatchRequest) returns (common.EmptyResponse);
}

message PrivateSearchResponse {
    repeated GenreWithTranslationsResponse genres = 1;
    optional common.PaginationResponse pagination = 2;
}

message PrivateSearchRequest {
    repeated string alias = 1;
    repeated string names = 2;
    repeated string language_codes = 3;
    optional common.PaginationRequest pagination = 4;
}

message PrivateCreateRequest {
    string alias = 1;
    int64 sort = 2;
}

message PrivateCreateBatchRequest {
    repeated PrivateCreateRequest genres = 1;
}

message PrivateUpdateRequest {
    int64 id = 1;
    string alias = 2;
    int64 sort = 3;
}

message PrivateDeleteRequest {
    int64 id = 1;
}

message PrivateDeleteBatchRequest {
    repeated int64 ids = 1;
}