syntax = "proto3";

package protos.services.content.genre;

import "common/common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.genre";
option java_outer_classname="GenrePublicProto";

service GenrePublicService {
    rpc search(SearchRequest) returns (SearchResponse);
}

message SearchRequest {
    repeated string alias = 1;
    repeated string name = 2;
    optional common.PaginationRequest pagination = 3;
}

message SearchResponse {
    repeated GenreWithTranslationResponse genres = 1;
    common.PaginationResponse pagination = 2;
}