syntax = "proto3";

package protos.services.content.genre;

import "common/common.proto";

option java_package="dev.animedia.grpc.genre";
option java_outer_classname="PrivateGenreProto";

service PrivateGenreService {
    rpc search(PrivateSearchGenreRequest) returns (PrivateSearchGenreResponse);
    rpc get(GetGenreRequest) returns (PrivateGenreResponse);
    rpc create(CreateGenreRequest) returns (PrivateGenreResponse);
    rpc update(UpdateGenreRequest) returns (PrivateGenreResponse);
    rpc delete(DeleteGenreRequest) returns (common.EmptyResponse);
}

message PrivateGenreResponse {
    string uuid = 1;
    string alias = 2;
    int32 sort_order = 3;
    bool active = 4;
    repeated PrivateGenreTranslationResponse translations = 5;
}

message PrivateGenreTranslationResponse {
    string uuid = 1;
    string genre_uuid = 2;
    string language_code = 3;
    string name = 4;
    optional string description = 5;
}

message PrivateSearchGenreRequest {
    optional bool active = 1;
    optional string alias = 2;
    optional string name = 3;
    optional string description = 4;
    optional string language_code = 5;
    optional common.PaginationRequest pagination = 6;
}

message PrivateSearchGenreResponse {
    repeated PrivateGenreResponse genres = 1;
    common.PaginationResponse pagination = 2;
}

message GetGenreRequest {
    string uuid = 1;
}

message CreateGenreRequest {
    string alias = 1;
    int32 sort_order = 2;
    bool active = 3;
    repeated CreateGenreTranslationRequest translations = 4;
}

message CreateGenreTranslationRequest {
    string language_code = 1;
    string name = 2;
    optional string description = 3;
}

message UpdateGenreRequest {
    string uuid = 1;
    int32 sort_order = 3;
    bool active = 4;
    repeated UpdateGenreTranslationRequest translations = 5;
}

message UpdateGenreTranslationRequest {
    optional string uuid = 1;
    string language_code = 2;
    string name = 3;
    optional string description = 4;
}

message DeleteGenreRequest {
    string uuid = 1;
}