syntax = "proto3";

package protos.services.content.genre;

import "common/common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.genre";
option java_outer_classname="PrivateGenreTranslationProto";

service PrivateGenreTranslationService {
    rpc search(PrivateTranslationSearchRequest) returns (PrivateTranslationSearchResponse);
    rpc create(PrivateTranslationCreateRequest) returns (GenreTranslationResponse);
    rpc update(PrivateTranslationUpdateRequest) returns (GenreTranslationResponse);
    rpc delete(PrivateTranslationDeleteRequest) returns (common.EmptyResponse);
    rpc deleteBatch(PrivateTranslationDeleteBatchRequest) returns (common.EmptyResponse);
}

message PrivateTranslationSearchRequest {
    optional int64 genre_id = 1;
    repeated string names = 2;
    repeated string language_codes = 3;
    common.PaginationRequest pagination = 4;
}

message PrivateTranslationSearchResponse {
    repeated GenreTranslationResponse translations = 1;
    common.PaginationResponse pagination = 2;
}

message PrivateTranslationCreateRequest {
    int64 genre_id = 1;
    string language_code = 2;
    string name = 3;
    string description = 4;
}

message PrivateTranslationUpdateRequest {
    int64 id = 1;
    int64 genre_id = 2;
    string language_code = 3;
    string name = 4;
    string description = 5;
}

message PrivateTranslationDeleteRequest {
    int64 id = 1;
}

message PrivateTranslationDeleteBatchRequest {
    repeated int64 ids = 1;
}