syntax = "proto3";

package protos.services.content.genre;

import "common/common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.genre";
option java_outer_classname="PrivateGenreProto";

service PrivateGenreService {
    rpc search(PrivateSearchRequest) returns (SearchGenreResponse);
    rpc create(CreateGenreRequest) returns (GenreResponse);
    rpc update(UpdateGenreRequest) returns (GenreResponse);
    rpc delete(DeleteGenreRequest) returns (common.EmptyResponse);
}

message PrivateSearchRequest {
    bool only_active = 1;
    optional string alias = 2;
    optional string name = 3;
    optional string description = 4;
    optional string language_code = 5;
    optional common.PaginationRequest pagination = 6;
}

message CreateGenreRequest {
    string alias = 1;
    int64 sort = 2;
}

message UpdateGenreRequest {
    int64 id = 1;
    string alias = 2;
    int64 sort = 3;
}

message DeleteGenreRequest {
    int64 id = 1;
}