syntax = "proto3";

package protos.services.content.core;

import "google/protobuf/timestamp.proto";
import "common/common.proto";
import "services/content/core/content_common.proto";
import "services/content/status/status_public.proto";
import "services/content/genre/genre_public.proto";

option java_package="dev.animedia.grpc.core";
option java_outer_classname="PublicContentProto";

service PublicContentService {
  rpc search(PublicSearchRequest) returns (PublicSearchResponse);
  rpc get(GetContentByDetailsRequest) returns (PublicContentResponse);
}

message PublicContentResponse {
  string alias = 1;
  Type type = 2;
  int32 season = 3;
  protos.services.content.status.PublicStatusResponse status = 4;
  optional string cover_image_uuid = 5;
  optional string trailer_video_uuid = 6;
  optional protos.common.Date release_date = 7;
  repeated string language_codes = 8;
  repeated protos.services.content.genre.PublicGenreResponse genres = 9;
  repeated PublicContentTranslationResponse translations = 10;
}

message PublicContentTranslationResponse {
  string title = 4;
  string description = 5;
}

message PublicSearchRequest {
  repeated string aliases = 1;
  repeated string titles = 2;
  repeated Type types = 3;
  repeated int32 seasons = 4;
  repeated int64 status_ids = 5;
  optional protos.common.Date release_date_from = 6;
  optional protos.common.Date release_date_to = 7;
  repeated string language_codes = 8;
  repeated int64 genre_ids = 9;
  optional protos.common.PaginationRequest pagination = 11;
}

message PublicSearchResponse {
  repeated PublicContentResponse contents = 1;
  protos.common.PaginationResponse pagination = 2;
}

message GetContentByDetailsRequest {
  string alias = 1;
  Type type = 2;
  int32 season = 3;
}