syntax = "proto3";

package protos.services.content.core;

import "google/protobuf/timestamp.proto";
import "common/common.proto";
import "services/content/core/content_common.proto";
import "services/content/status/status_private.proto";
import "services/content/genre/genre_private.proto";

option java_package="dev.animedia.grpc.core";
option java_outer_classname="PrivateContentProto";

service PrivateContentService {
  rpc search(PrivateSearchContentRequest) returns (PrivateSearchContentResponse);
  rpc get(GetContentRequest) returns (PrivateContentResponse);
  rpc create(CreateContentRequest) returns (PrivateContentResponse);
  rpc update(UpdateContentRequest) returns (PrivateContentResponse);
  rpc delete(DeleteContentRequest) returns (common.EmptyResponse);
}

message PrivateContentResponse {
  string uuid = 1;
  string alias = 2;
  Type type = 3;
  optional int32 season = 4;
  protos.services.content.status.PrivateStatusResponse status = 5;
  optional string cover_image_uuid = 6;
  optional string trailer_video_uuid = 7;
  optional protos.common.Date release_date = 8;
  google.protobuf.Timestamp created_at = 9;
  optional google.protobuf.Timestamp updated_at = 10;
  bool active = 11;
  repeated string language_codes = 12;
  repeated protos.services.content.genre.PrivateGenreResponse genres = 13;
  repeated PrivateContentTranslationResponse translations = 14;
}

message PrivateContentTranslationResponse {
  string uuid = 1;
  string content_uuid = 2;
  string language_code = 3;
  string title = 4;
  string description = 5;
}

message PrivateSearchContentRequest {
  optional string uuid = 1;
  repeated string aliases = 2;
  repeated string titles = 3;
  repeated Type types = 4;
  repeated int32 seasons = 5;
  repeated int64 status_ids = 6;
  optional protos.common.Date release_date_from = 7;
  optional protos.common.Date release_date_to = 8;
  optional google.protobuf.Timestamp created_at_from = 9;
  optional google.protobuf.Timestamp created_at_to = 10;
  optional google.protobuf.Timestamp updated_at_from = 11;
  optional google.protobuf.Timestamp updated_at_to = 12;
  optional bool active = 13;
  repeated string language_codes = 14;
  repeated int64 genre_ids = 15;
  optional protos.common.PaginationRequest pagination = 17;
}

message PrivateSearchContentResponse {
  repeated PrivateContentResponse contents = 1;
  common.PaginationResponse pagination = 2;
}

message GetContentRequest {
  string uuid = 1;
}

message CreateContentRequest {
  string alias = 1;
  Type type = 2;
  int32 season = 3;
  optional int64 status_id = 4;
  optional string cover_image_uuid = 5;
  optional string trailer_video_uuid = 6;
  optional protos.common.Date release_date = 7;
  bool active = 10;
  optional int32 sort = 11;
  repeated string language_codes = 12;
  repeated int64 genre_ids = 13;
}

message UpdateContentRequest {
  string uuid = 1;
  optional int64 status_id = 5;
  optional string cover_image_uuid = 6;
  optional string trailer_video_uuid = 7;
  optional protos.common.Date release_date = 8;
  optional bool active = 11;
  optional int32 sort = 12;
  repeated string language_codes = 13;
  repeated int64 genre_ids = 14;
}

message UpdateContentTranslationRequest {
  optional string uuid = 1;
  string language_code = 2;
  string title = 3;
  optional string description = 4;
}

message DeleteContentRequest {
  string uuid = 1;
}