syntax = "proto3";

package protos.services.content.core;

import "google/protobuf/timestamp.proto";
import "common/common.proto";
import "services/content/core/content_common.proto";
import "services/content/status/content_status_common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.core";
option java_outer_classname="PrivateContentProto";

service PrivateContentService {
  rpc search(PrivateSearchRequest) returns (PrivateSearchResponse);
  rpc create(PrivateCreateRequest) returns (PrivateContentResponse);
  rpc update(PrivateUpdateRequest) returns (PrivateContentResponse);
  rpc delete(PrivateDeleteRequest) returns (common.EmptyResponse);
}

message PrivateSearchRequest {
  optional string uuid = 1;
  optional string alias = 2;
  optional string title = 3;
  repeated ContentType type = 4;
  repeated int32 seasons = 5;
  repeated int64 content_status_ids = 6;
  optional protos.common.Date release_date_from = 7;
  optional protos.common.Date release_date_to = 8;
  optional google.protobuf.Timestamp created_at_from = 9;
  optional google.protobuf.Timestamp created_at_to = 10;
  optional google.protobuf.Timestamp updated_at_from = 11;
  optional google.protobuf.Timestamp updated_at_to = 12;
  optional bool active = 13;
  repeated string language_codes = 14;
  repeated int64 genre_ids = 15;
  optional Sort sort = 16;
  optional protos.common.PaginationRequest pagination = 17;
}

message PrivateSearchResponse {
  repeated PrivateContentResponseWithTranslationList contents = 1;
  common.PaginationResponse pagination = 2;
}

message PrivateCreateRequest {
  string alias = 1;
  ContentType type = 2;
  int32 season = 3;
  protos.services.content.status.ContentStatusWithTranslationResponse status = 4;
  string cover_url = 5;
  string trailer_url = 6;
  protos.common.Date release_date = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  bool active = 10;
  repeated string language_codes = 11;
  repeated protos.services.content.genre.GenreWithTranslationResponse genres = 12;
}

message PrivateUpdateRequest {
  string uuid = 1;
  string alias = 2;
  ContentType type = 3;
  int32 season = 4;
  protos.services.content.status.ContentStatusWithTranslationResponse status = 5;
  string cover_url = 6;
  string trailer_url = 7;
  protos.common.Date release_date = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  bool active = 11;
  repeated string language_codes = 12;
  repeated protos.services.content.genre.GenreWithTranslationResponse genres = 13;
}

message PrivateDeleteRequest {
  string uuid = 1;
}

message PrivateContentResponse {
  string uuid = 1;
  string alias = 2;
  ContentType type = 3;
  int32 season = 4;
  protos.services.content.status.ContentStatusWithTranslationResponse status = 5;
  string cover_url = 6;
  string trailer_url = 7;
  protos.common.Date release_date = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  bool active = 11;
  repeated string language_codes = 12;
  repeated protos.services.content.genre.GenreWithTranslationResponse genres = 13;
}

message PrivateContentResponseWithTranslationList {
  PrivateContentResponse content = 1;
  repeated ContentTranslationResponse translations = 2;
}