syntax = "proto3";

package protos.services.content.core;

import "google/protobuf/timestamp.proto";
import "common/common.proto";
import "services/content/core/content_common.proto";
import "services/content/status/content_status_common.proto";
import "services/content/genre/genre_common.proto";

option java_package="dev.animedia.grpc.core";
option java_outer_classname="ContentPublicProto";

service ContentPublicService {
  rpc search(SearchRequest) returns (SearchResponse);
  rpc get(GetRequest) returns (ContentPublicResponseWithTranslation);
}

message SearchRequest {
  optional string alias = 1;
  repeated ContentType type = 2;
  repeated int32 seasons = 3;
  repeated int64 content_status_ids = 4;
  optional google.protobuf.Timestamp release_date_from = 5;
  optional google.protobuf.Timestamp release_date_to = 6;
  repeated string language_codes = 7;
  optional SortBy sort_by = 8;
  optional protos.common.SortType sort_type = 9;
  optional protos.common.PaginationRequest pagination = 10;
}

enum SortBy {
  RELEASE_DATE = 0;
  SORT = 1;
}

message SearchResponse {
  repeated ContentPublicResponseWithTranslation contents = 1;
  protos.common.PaginationResponse pagination = 2;
}

message GetRequest {
  string alias = 1;
}

message ContentPublicResponse {
  string uuid = 1;
  string alias = 2;
  ContentType type = 3;
  int32 season = 4;
  protos.services.content.status.ContentStatusWithTranslationResponse status = 5;
  string cover_url = 6;
  string trailer_url = 7;
  google.protobuf.Timestamp release_date = 8;
  repeated string language_codes = 9;
  repeated protos.services.content.genre.GenreWithTranslationResponse genres = 10;
}

message ContentPublicResponseWithTranslation {
  ContentPublicResponse content = 1;
  ContentTranslationResponse translation = 2;
}