package dev.animedia.contentservice.contentstatus;

public class ContentStatusConstants {

	public static final String CONTENT_STATUS_LANGUAGE_ID_REQUIRED_MESSAGE = "CONTENT_STATUS_LANGUAGE_ID_REQUIRED";
	public static final String CONTENT_STATUS_LANGUAGE_ALIAS_REQUIRED_MESSAGE = "CONTENT_STATUS_LANGUAGE_ALIAS_REQUIRED";

	public static final String CONTENT_STATUS_ALIAS_EXISTS_MESSAGE = "CONTENT_STATUS_ALIAS_EXISTS";
	public static final String CONTENT_STATUS_NOT_FOUND_MESSAGE = "CONTENT_STATUS_NOT_FOUND";
	public static final String CONTENT_STATUS_TRANSLATION_EXISTS_MESSAGE = "CONTENT_STATUS_TRANLATION_EXISTS";
	public static final String CONTENT_STATUS_TRANSLATION_NOT_FOUND_MESSAGE = "CONTENT_STATUS_TRANSLATION_NOT_FOUND";
	public static final String CONTENT_STATUS_TRANSLATIONS_NOT_FOUND_MESSAGE = "CONTENT_STATUS_TRANSLATIONS_NOT_FOUND";
	public static final String CONTENT_STATUS_ID_REQUIRED_MESSAGE = "CONTENT_STATUS_ID_REQUIRED";
	public static final String CONTENT_STATUS_NAME_REQUIRED_MESSAGE = "CONTENT_STATUS_NAME_REQUIRED";

	private ContentStatusConstants() {}
}
