spring.application.name=content-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5444/content
spring.datasource.username=animedia
spring.datasource.password=password

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

application.exception.locale.path=errors/
